#+title: Automatización con Proxmox 
#+author: Luciano Daniel Diamand
#+email: lucianodiamand@gmail.com

* Scripts

** Instalar kubernetes vm

#+begin_src bash
./create_kubernetes_base.sh

# Estaria bueno antes de hacer el siguiente paso crear una snapshot

# luego de la instalacion queda bloqueado y tira:
# Reading package lists...
# E: Could not get lock /var/lib/apt/lists/lock. It is held by process 478 (apt-get)
# E: Unable to lock directory /var/lib/apt/lists/
#
# por lo tanto hacemos un sleep:
sleep 60

./bootstrap-k3s.sh
./install-ci-gitops.sh
#+end_src

Hay que sacar los siguientes mensajes de error:

bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.UTF-8",
	LC_TIME = "es_AR.UTF-8",
	LC_MONETARY = "es_AR.UTF-8",
	LC_ADDRESS = "es_AR.UTF-8",
	LC_TELEPHONE = "es_AR.UTF-8",
	LC_NAME = "es_AR.UTF-8",
	LC_MEASUREMENT = "es_AR.UTF-8",
	LC_IDENTIFICATION = "es_AR.UTF-8",
	LC_NUMERIC = "es_AR.UTF-8",
	LC_PAPER = "es_AR.UTF-8",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.UTF-8",
	LC_TIME = "es_AR.UTF-8",
	LC_MONETARY = "es_AR.UTF-8",
	LC_ADDRESS = "es_AR.UTF-8",
	LC_TELEPHONE = "es_AR.UTF-8",
	LC_NAME = "es_AR.UTF-8",
	LC_MEASUREMENT = "es_AR.UTF-8",
	LC_IDENTIFICATION = "es_AR.UTF-8",
	LC_NUMERIC = "es_AR.UTF-8",
	LC_PAPER = "es_AR.UTF-8",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").


Tambien el siguiente:

WARNING: You have not turned on protection against thin pools running out of space.
  WARNING: Set activation/thin_pool_autoextend_threshold below 100 to trigger automatic extension of thin pools before they get full.
  Logical volume "snap_vm-801-disk-0_install" created.
  WARNING: Sum of all thin volume sizes (864.72 GiB) exceeds the size of thin pool pve/data and the amount of free space in volume group (16.00 GiB).
TASK OK

Agregar confirmacion de borrar


