profiles:
  - name: production
    vpn_config: <openfortivpn_config_file>
    otp_prompt: "Two-factor authentication token:"
    search_delay: 2s
    search_sender: <sender>
    search_mailbox: OTP
    search_within: 60s
    search_field: Subject
    search_regex: 'Token code: (\d+)'
    imap:
      host: imap.gmail.com
      port: 993
      username: <email>
      password: <password>
